name: CICD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: build and push image
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
        
      - name: Build and push
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/andrewscherer.info:latest ./web/backend
          docker push ${{ secrets.DOCKER_USERNAME }}/andrewscherer.info:latest
      
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            docker compose -f web/docker-compose.yml down
            docker compose -f web/docker-compose.yml pull
            docker compose -f web/docker-compose.yml up -d --build


